from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import unittest

class SeleniumTest(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()       
        self.driver.get('localhost:8000/')

    def test_asignup(self):
        menu = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar")))
        signup = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar #signup")))
        actions = webdriver.ActionChains(self.driver)
        actions.move_to_element(menu)
        actions.click(signup)
        actions.perform()
        form_name = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "name")))
        form_name.send_keys("s")
        form_user = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "email")))
        form_user.send_keys("s")
        form_pass = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "password")))
        form_pass.send_keys("s")
        form_phone = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "phone")))
        form_phone.send_keys("s")
        form_desc = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, "#id_description")))
        form_desc.send_keys("s")
        form_submit = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, "#button")))
        form_submit.submit()

    def test_login(self):
        menu = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar")))
        login = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar #login")))
        actions = webdriver.ActionChains(self.driver)
        actions.move_to_element(menu)
        actions.click(login)
        actions.perform()
        form_email = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "email")))
        form_email.send_keys("s")
        form_pass = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "password")))
        form_pass.send_keys("s")
        form_submit = self.driver.find_element_by_css_selector("#button")
        form_submit.submit()
        menu = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar")))
        logout = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar #logout")))
        actions = webdriver.ActionChains(self.driver)
        actions.move_to_element(menu)
        actions.click(logout)
        actions.perform()

    def test_create_posting(self):
        menu = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar")))
        login = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar #login")))
        actions = webdriver.ActionChains(self.driver)
        actions.move_to_element(menu)
        actions.click(login)
        actions.perform()
        form_email = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "email")))
        form_email.send_keys("s")
        form_pass = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "password")))
        form_pass.send_keys("s")
        form_submit = self.driver.find_element_by_css_selector("#button")
        form_submit.submit()
        menu = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar")))
        listing = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar #listing")))
        actions = webdriver.ActionChains(self.driver)
        actions.move_to_element(menu)
        actions.click(listing)
        actions.perform()
        form_course = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "course_name")))
        form_course.send_keys("s")
        form_tag = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "tag")))
        form_tag.send_keys("s")
        form_desc = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, "#id_description")))
        form_desc.send_keys("s")
        form_qual = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "qualification")))
        form_qual.send_keys("s")
        form_times = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "times")))
        form_times.send_keys("3:00 PM")
        form_price = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "price")))
        form_price.send_keys("30")
        form_submit = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, "#button")))
        form_submit.submit()

    def test_create_posting_without_login(self):
        menu = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar")))
        listing = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar #listing")))
        actions = webdriver.ActionChains(self.driver)
        actions.move_to_element(menu)
        actions.click(listing)
        actions.perform()
        form_email = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "email")))
        form_email.send_keys("s")
        form_pass = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "password")))
        form_pass.send_keys("s")
        form_submit = self.driver.find_element_by_css_selector("#button")
        form_submit.submit()
        menu = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar")))
        listing = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar #listing")))
        actions = webdriver.ActionChains(self.driver)
        actions.move_to_element(menu)
        actions.click(listing)
        actions.perform()
        form_course = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "course_name")))
        form_course.send_keys("s")
        form_tag = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "tag")))
        form_tag.send_keys("s")
        form_desc = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, "#id_description")))
        form_desc.send_keys("s")
        form_qual = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "qualification")))
        form_qual.send_keys("s")
        form_times = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "times")))
        form_times.send_keys("3:00 PM")
        form_price = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "price")))
        form_price.send_keys("30")
        form_submit = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, "#button")))
        form_submit.submit()


    def test_courses(self):
        menu = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar")))
        login = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar #login")))
        actions = webdriver.ActionChains(self.driver)
        actions.move_to_element(menu)
        actions.click(login)
        actions.perform()
        form_email = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "email")))
        form_email.send_keys("s")
        form_pass = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.NAME, "password")))
        form_pass.send_keys("s")
        form_submit = self.driver.find_element_by_css_selector("#button")
        form_submit.submit()
        menu = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar")))
        courses = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar #courses")))
        actions = webdriver.ActionChains(self.driver)
        actions.move_to_element(menu)
        actions.click(courses)
        actions.perform()

    def test_search(self):
        menu = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".navbar")))
        form_search = WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, "#query")))
        form_search.send_keys("Python")
        form_submit = self.driver.find_element_by_css_selector("#sbutton")
        form_submit.submit()


    #signup, login, create page, try to create page without being logged in
    def tearDown(self):
        self.driver.quit()
if __name__ == '__main__':
    unittest.main()
